"""add candidate_embeddings table

Revision ID: ff92b2b050b1
Revises: 8674bdf66c49
Create Date: 2026-08-21 23:18:02.086421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ff92b2b050b1'
down_revision: Union[str, Sequence[str], None] = '8674bdf66c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['public.candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('candidate_embeddings_candidate_id_idx', 'candidate_embeddings', ['candidate_id'], unique=False, schema='public')
    op.create_index('candidate_embeddings_embedding_idx', 'candidate_embeddings', ['embedding'], unique=False, schema='public', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('candidate_embeddings_embedding_idx', table_name='candidate_embeddings', schema='public', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('candidate_embeddings_candidate_id_idx', table_name='candidate_embeddings', schema='public')
    op.drop_table('candidate_embeddings', schema='public')
    # ### end Alembic commands ###
